# Generated by Django 5.1.2 on 2024-10-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aadhar',
            name='id',
        ),
        migrations.AlterField(
            model_name='aadhar',
            name='aadhar',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
