# Generated by Django 5.1.2 on 2024-10-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_aadhar_id_alter_aadhar_aadhar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Stu_contact',
            field=models.IntegerField(),
        ),
    ]
