# Generated by Django 5.1.2 on 2024-10-25 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_profile_expe_alter_profile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='aadhar_no',
        ),
        migrations.RemoveField(
            model_name='student',
            name='dep_name',
        ),
        migrations.DeleteModel(
            name='Aadhar',
        ),
        migrations.DeleteModel(
            name='department',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
